# Generated by Django 5.1.7 on 2025-03-12 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продажу')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.employee', verbose_name='Працівник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продаж',
                'verbose_name_plural': 'Продажі',
            },
        ),
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('target_amount', models.IntegerField(verbose_name='Цільова кількість')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'План продажів',
                'verbose_name_plural': 'Плани продажів',
            },
        ),
    ]
